version: '3.1'
services:
  node:
    ports:
      - '3000:3000'
      - '3001:3001'
    restart: "no"
    volumes:
      - ./../../../../nginx-load-balancer/docker/mkcert/openstate.eu/:/certs/
    networks:
      - nginx-load-balancer
networks:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
